### ISSUE TITLE
Legebesøk, kiropraktor

### ISSUE THREAD

**Issue by hnilsen** [apparatno/company#13]
Vi bør være tydeligere i personalhåndboken hva som gjelder når man er hos legen, kiropraktor eller annet. Forslaget mitt er å skrive en generell formulering om at dette står man fritt til å gjøre uten at det må jobbes inn igjen. Spørsmålet om det skal kompenseres for i forhold til provisjon? @eaardal @fiskeben - tanker?

**Comment by fiskeben** [comment]
Enig i det. Jeg synes det må være på sin plass med en kompensasjon, for eksempel opptil n timer per år eller en prosentsats. Jeg tenker spesielt på at gravide ofte må til legen og lignende, og det synes jeg ikke de skal straffes for.

**Comment by hnilsen** [comment]
Fører enn en slik seksjon:
```
### Lønn ved besøk til lege og kiropraktor

Vi fører besøk til lege og kiropraktor som arbeidstid, men uten provisjon for de som har det. Det vil ikke bli trukket i fast- eller garantilønn for slikt.

```
